# Generated by Django 6.0.1 on 2026-03-30 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_pedido_elementopedido"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categoria",
            options={"verbose_name_plural": "Categorias"},
        ),
        migrations.AddField(
            model_name="categoria",
            name="orden",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="categoria",
            name="slug",
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productos",
                to="store.categoria",
            ),
        ),
    ]
